home/urls.py
from django.urls import path,include
from .views import *

from rest_framework import routers
router = routers.DefaultRouter()


# router.register(r'data', apiViewSet,'data'),
router.register(r'data', studentViewSet, 'home'),

urlpatterns = [
    # path('student/', student),
    # path('signup/', signup),
    path('login/', login),
    path('logout/', logout),
    path('adminsite/', adminsite,name="admin site"),
    path('addstudent/', studentRegister,name="studentRegister"),
    path('active/', activeStudent,name="activeStudent"),
    path('inactive/', inactiveStudent,name="inactiveStudent"),
    path('status/<int:id>', studentStatus,name="studentStatus"),
    path('studentDetails/', studentDetails,name="studentDetails"),
    path('updatedetails/', updateStudent,name="updateStudent"),

    # api
    # path('apiview/',apiView,name="apiView"),
    # path('apiview/<int:id>/',apiView,name="apiView"),
    
    # path('apidata/',apiViewSet.as_view(),name="apiViewSet"),
    path('studentdata/',sdatViewSet.as_view(),name="sdatViewSet"),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
    # path('std',student.as_view(),name='std'),
    path('students/',studentDtails,name="studentDtails"),
    path('students/<int:id>/',studentDtails,name="studentDtails"),
    path('studenthome/',studentHome,name="studentHome"),
    path('studenthome/<int:id>/',studentHome,name="studentHome"),
    path('userlogin/',userLogin,name="userLogin"),
]

studentManagementSystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('accounts/',include('accounts.urls')),
]

home/forms.py
from django import forms
from .models import *
from accounts.models import myUser


class studentRegisterForm(forms.ModelForm):
    name=forms.CharField(max_length=254)
    contact =forms.CharField(max_length=15)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    status = forms.CharField(max_length=20)
    rule = forms.CharField(max_length=20)
    # password1=forms.CharField(max_length=50)
    # password2=forms.CharField(max_length=50)
    class Meta:
        model=myUser
        fields = ('name','email','username','contact','status','rule','password')

templates/student/studentsite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StudentManagementSystem</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>
<body>
    {% include 'topnav.html'%}
    <div class="container-fluid mt-2 text-center">
        <div class="row">
            <div class="col-md-3">
                <div class="card p-3">
                    {% include 'sidenavstd.html'%}
                </div>
            </div>
            <div class="col-md-9">
                <div class="card">
                    <h1>student details</h1>
                </div>
                
             

                <table class="table table-bordered mt-4">
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">name</th>
                            <th scope="col">username</th>
                            <th scope="col">contact</th>
                            <th scope="col">email</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for p in student_dtl %}
                        <tr>
                            <td>{{p.id}}</td>
                            <td>{{p.name}}</td>
                            <td>{{p.username}}</td>
                            <td>{{p.contact}}</td>
                            <td>{{p.email}}</td>
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>

            </div>
           
            <!-- <div class="col-md-3">
                <div class="card">
                    <h1>details</h1>
                </div>
            </div> -->
        </div>

    </div>
</body>
</html>

templates/student/studentupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StudentManagementSystem</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    <script>
        $(document).ready(function() {
                $('#id_contact').blur(function() {
                    var mobNum = $(this).val();
                    var filter = /^\d*(?:\.\d{1,2})?$/;
    
              if (filter.test(mobNum)) {
                if(mobNum.length==10){
                      console.log("contact")
                 } else {
                    $('#mobile-valid').html('Please put 10  digit mobile number').css('color', 'red');
                    return false;
                  }
                }
                else {
                  $('#mobile-valid').html('Not a valid number').css('color', 'red');
                  return false;
               }
    
                });
        });
    
    
        $(document).ready(function() {
                $('#id_password').blur(function() {
                    if ($('#id_password').val().length < 5) {
                        console.log("paas")
                        $(':input[type="submit"]').prop('disabled', true)
                        $('#msg_pass').html('password must be more than 5 characters').css('color', 'red')
                    } else if ($('#id_password').val().length > 10) {
                        console.log("no")
                        $(':input[type="submit"]').prop('disabled', true)
                        $('#msg_pass').html('password must be less than 10 characters').css('color', 'red')
                    } else {
                        $(':input[type="submit"]').prop('disabled', false)
                        $('#msg_pass').html('paasword must be in 5-10').css('color', 'black')
                    }
                });
            });
    
            $(document).ready(function() {
                $('#id_password2').on('keyup', function() {
                    if ($('#id_password').val() == $('#id_password2').val()) {
                        $('#message').html('').css('color', 'green');
                        $(':input[type="submit"]').prop('disabled', false);
                    } else
                        $(':input[type="submit"]').prop('disabled', true),
                        $('#message').html('Not Matching passwords').css('color', 'red');
                });
            });

        </script>


</head>
<body>
    {% include 'topnav.html'%}
    <div class="container-fluid mt-2 text-center">
        <div class="row">
            <div class="col-md-3">
                <div class="card p-3">
                    {% include 'sidenavstd.html'%}
                </div>
            </div>
            <div class="col-md-9">
                <div class="card">
                    <h1>Update details</h1>
                </div>

                <form action="" method="POST"  enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row mt-4">
                        <div class="col-sm-6 ">
                        <input type="text" class="form-control" name="name" maxlength="254" required="" id="id_name" placeholder="{{ student_dtl.name }}" value="{{ student_dtl.name }}">
                        </div>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" name="username" maxlength="254" required="" id="id_username" placeholder="{{ student_dtl.username }}" value="{{ student_dtl.username }}">
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col-sm-6 ">
                        <input type="text" class="form-control" name="contact" maxlength="254" required="" id="id_contact" placeholder="{{ student_dtl.contact }}" value="{{ student_dtl.contact }}">
                        <label for="" id="mobile-valid" class="hidden mob"></label>
                        </div>
                        <div class="col-sm-6">
                            <input type="email" class="form-control" name="email" maxlength="254" required="" id="id_email" placeholder="{{ student_dtl.email }}" value="{{ student_dtl.email }}">
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col-sm-6 ">
                        <input type="text" class="form-control" name="password" maxlength="254" required="" id="id_password" placeholder="{{ student_dtl.password }}" value="{{ student_dtl.password }}">
                        <label for="" id="msg_pass"></label>
                        </div>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" name="password2" maxlength="254"  id="id_password2" placeholder="confirm password">
                            <label for="" id="message"></label>
                        </div>
                    </div>
                    <input type="hidden" value="student" name="rule" maxlength="20" required="" id="id_rule">
                    <input type="hidden" value="active" name="status" maxlength="20" required="" id="id_status">
                    
                        <button type="submit" class="btn btn-info mt-4">Update data</button>
                    </div>
                </form>
               
                
            </div>
        </div>

    </div>
</body>
</html>